#  ['google', 'google_news', 'bing', 'bing_news', 'duckduckgo', 'yahoo', 'yandex', 'gdelt', 'copyscape']

DEFAULTS = {
    "search_engines": ["all"],
    "language": "en",
    "country": "us",
}
ENGINES = {
    "google": "Google",
    "bing": "Bing",
    "duckduckgo": "DuckDuckGo",
    "yandex": "Yandex",
    "gdelt": "GDELT",
    "copyscape": "Copyscape",
    "google_news": "Google News",
    "bing_news": "Bing News"
}    
LANGUAGES = {
'af':	'Afrikaans',
'ak':	'Akan',
'sq':	'Albanian',
'ws':	'Samoa',
'am':	'Amharic',
'ar':	'Arabic',
'hy':	'Armenian',
'az':	'Azerbaijani',
'eu':	'Basque',
'be':	'Belarusian',
'bem':	'Bemba',
'bn':	'Bengali',
'bh':	'Bihari',
'bs':	'Bosnian',
'br':	'Breton',
'bg':	'Bulgarian',
'bt':	'Bhutanese',
'km':	'Cambodian',
'ca':	'Catalan',
'chr':	'Cherokee',
'ny':	'Chichewa',
'zh-cn':	'Chinese (Simplified)',
'zh-tw':	'Chinese (Traditional)',
'co':	'Corsican',
'hr':	'Croatian',
'cs':	'Czech',
'da':	'Danish',
'nl':	'Dutch',
'en':	'English',
'eo':	'Esperanto',
'et':	'Estonian',
'ee':	'Ewe',
'fo':	'Faroese',
'tl':	'Filipino',
'fi':	'Finnish',
'fr':	'French',
'fy':	'Frisian',
'gaa':	'Ga',
'gl':	'Galician',
'ka':	'Georgian',
'de':	'German',
'el':	'Greek',
'kl':	'Greenlandic',
'gn':	'Guarani',
'gu':	'Gujarati',
'ht':	'Haitian Creole',
'ha':	'Hausa',
'haw':	'Hawaiian',
'iw':	'Hebrew',
'hi':	'Hindi',
'hu':	'Hungarian',
'is':	'Icelandic',
'ig':	'Igbo',
'id':	'Indonesian',
'ia':	'Interlingua',
'ga':	'Irish',
'it':	'Italian',
'ja':	'Japanese',
'jw':	'Javanese',
'kn':	'Kannada',
'kk':	'Kazakh',
'rw':	'Kinyarwanda',
'rn':	'Kirundi',
'kg':	'Kongo',
'ko':	'Korean',
'kri':	'Krio (Sierra Leone)',
'ku':	'Kurdish',
'ckb':	'Kurdish (Soranî)',
'ky':	'Kyrgyz',
'lo':	'Laothian',
'la':	'Latin',
'lv':	'Latvian',
'ln':	'Lingala',
'lt':	'Lithuanian',
'loz':	'Lozi',
'lg':	'Luganda',
'ach':	'Luo',
'mk':	'Macedonian',
'mg':	'Malagasy',
'ms':	'Malay',
'ml':	'Malayalam',
'mt':	'Maltese',
'mv':	'Maldives',
'mi':	'Maori',
'mr':	'Marathi',
'mfe':	'Mauritian Creole',
'mo':	'Moldavian',
'mn':	'Mongolian',
'sr-me':	'Montenegrin',
'my':	'Myanmar',
'ne':	'Nepali',
'pcm':	'Nigerian Pidgin',
'nso':	'Northern Sotho',
'no':	'Norwegian',
'nn':	'Norwegian (Nynorsk)',
'oc':	'Occitan',
'or':	'Oriya',
'om':	'Oromo',
'ps':	'Pashto',
'fa':	'Persian',
'pl':	'Polish',
'pt':	'Portuguese',
'pt-br':	'Portuguese (Brazil)',
'pt-pt':	'Portuguese (Portugal)',
'pa':	'Punjabi',
'qu':	'Quechua',
'ro':	'Romanian',
'rm':	'Romansh',
'nyn':	'Runyakitara',
'ru':	'Russian',
'gd':	'Scots Gaelic',
'sr':	'Serbian',
'sh':	'Serbo-Croatian',
'st':	'Sesotho',
'tn':	'Setswana',
'crs':	'Seychellois Creole',
'sn':	'Shona',
'sd':	'Sindhi',
'si':	'Sinhalese',
'sk':	'Slovak',
'sl':	'Slovenian',
'so':	'Somali',
'es':	'Spanish',
'es-419':	'Spanish (Latin American)',
'su':	'Sundanese',
'sw':	'Swahili',
'sv':	'Swedish',
'tg':	'Tajik',
'ta':	'Tamil',
'tt':	'Tatar',
'te':	'Telugu',
'th':	'Thai',
'ti':	'Tigrinya',
'to':	'Tonga',
'lua':	'Tshiluba',
'tum':	'Tumbuka',
'tr':	'Turkish',
'tk':	'Turkmen',
'tw':	'Twi',
'ug':	'Uighur',
'uk':	'Ukrainian',
'ur':	'Urdu',
'uz':	'Uzbek',
'vu':	'Vanuatu',
'vi':	'Vietnamese',
'cy':	'Welsh',
'wo':	'Wolof',
'xh':	'Xhosa',
'yi':	'Yiddish',
'yo':	'Yoruba',
'zu':	'Zulu'
}

COUNTRIES = {
'af':	'Afghanistan',
'al':	'Albania',
'dz':	'Algeria',
'as':	'American Samoa',
'ad':	'Andorra',
'ao':	'Angola',
'ai':	'Anguilla',
'aq':	'Antarctica',
'ag':	'Antigua and Barbuda',
'ar':	'Argentina',
'am':	'Armenia',
'aw':	'Aruba',
'au':	'Australia',
'at':	'Austria',
'az':	'Azerbaijan',
'bs':	'Bahamas',
'bh':	'Bahrain',
'bd':	'Bangladesh',
'bb':	'Barbados',
'by':	'Belarus',
'be':	'Belgium',
'bz':	'Belize',
'bj':	'Benin',
'bm':	'Bermuda',
'bt':	'Bhutan',
'bo':	'Bolivia',
'ba':	'Bosnia and Herzegovina',
'bw':	'Botswana',
'bv':	'Bouvet Island',
'br':	'Brazil',
'io':	'British Indian Ocean Territory',
'bn':	'Brunei Darussalam',
'bg':	'Bulgaria',
'bf':	'Burkina Faso',
'bi':	'Burundi',
'kh':	'Cambodia',
'cm':	'Cameroon',
'ca':	'Canada',
'cv':	'Cape Verde',
'ky':	'Cayman Islands',
'cf':	'Central African Republic',
'td':	'Chad',
'cl':	'Chile',
'cn':	'China',
'cx':	'Christmas Island',
'cc':	'Cocos (Keeling) Islands',
'co':	'Colombia',
'km':	'Comoros',
'cg':	'Congo',
'cd':	'Congo, the Democratic Republic of the',
'ck':	'Cook Islands',
'cr':	'Costa Rica',
'ci':	'Cote D\'ivoire',
'hr':	'Croatia',
'cu':	'Cuba',
'cy':	'Cyprus',
'cz':	'Czech Republic',
'dk':	'Denmark',
'dj':	'Djibouti',
'dm':	'Dominica',
'do':	'Dominican Republic',
'ec':	'Ecuador',
'eg':	'Egypt',
'sv':	'El Salvador',
'gq':	'Equatorial Guinea',
'er':	'Eritrea',
'ee':	'Estonia',
'et':	'Ethiopia',
'fk':	'Falkland Islands (Malvinas)',
'fo':	'Faroe Islands',
'fj':	'Fiji',
'fi':	'Finland',
'fr':	'France',
'gf':	'French Guiana',
'pf':	'French Polynesia',
'tf':	'French Southern Territories',
'ga':	'Gabon',
'gm':	'Gambia',
'ge':	'Georgia',
'de':	'Germany',
'gh':	'Ghana',
'gi':	'Gibraltar',
'gr':	'Greece',
'gl':	'Greenland',
'gd':	'Grenada',
'gp':	'Guadeloupe',
'gu':	'Guam',
'gt':	'Guatemala',
'gn':	'Guinea',
'gw':	'Guinea-Bissau',
'gy':	'Guyana',
'ht':	'Haiti',
'hm':	'Heard Island and Mcdonald Islands',
'va':	'Holy See (Vatican City State)',
'hn':	'Honduras',
'hk':	'Hong Kong',
'hu':	'Hungary',
'is':	'Iceland',
'in':	'India',
'id':	'Indonesia',
'ir':	'Iran, Islamic Republic of',
'iq':	'Iraq',
'ie':	'Ireland',
'il':	'Israel',
'it':	'Italy',
'jm':	'Jamaica',
'jp':	'Japan',
'jo':	'Jordan',
'kz':	'Kazakhstan',
'ke':	'Kenya',
'ki':	'Kiribati',
'kp':	'Korea, Democratic People\'s Republic of',
'kr':	'Korea, Republic of',
'kw':	'Kuwait',
'kg':	'Kyrgyzstan',
'la':	'Lao People\'s Democratic Republic',
'lv':	'Latvia',
'lb':	'Lebanon',
'ls':	'Lesotho',
'lr':	'Liberia',
'ly':	'Libyan Arab Jamahiriya',
'li':	'Liechtenstein',
'lt':	'Lithuania',
'lu':	'Luxembourg',
'mo':	'Macao',
'mk':	'Macedonia, the Former Yugosalv Republic of',
'mg':	'Madagascar',
'mw':	'Malawi',
'my':	'Malaysia',
'mv':	'Maldives',
'ml':	'Mali',
'mt':	'Malta',
'mh':	'Marshall Islands',
'mq':	'Martinique',
'mr':	'Mauritania',
'mu':	'Mauritius',
'yt':	'Mayotte',
'mx':	'Mexico',
'fm':	'Micronesia, Federated States of',
'md':	'Moldova, Republic of',
'mc':	'Monaco',
'mn':	'Mongolia',
'ms':	'Montserrat',
'ma':	'Morocco',
'mz':	'Mozambique',
'mm':	'Myanmar',
'na':	'Namibia',
'nr':	'Nauru',
'np':	'Nepal',
'nl':	'Netherlands',
'an':	'Netherlands Antilles',
'nc':	'New Caledonia',
'nz':	'New Zealand',
'ni':	'Nicaragua',
'ne':	'Niger',
'ng':	'Nigeria',
'nu':	'Niue',
'nf':	'Norfolk Island',
'mp':	'Northern Mariana Islands',
'no':	'Norway',
'om':	'Oman',
'pk':	'Pakistan',
'pw':	'Palau',
'ps':	'Palestinian Territory, Occupied',
'pa':	'Panama',
'pg':	'Papua New Guinea',
'py':	'Paraguay',
'pe':	'Peru',
'ph':	'Philippines',
'pn':	'Pitcairn',
'pl':	'Poland',
'pt':	'Portugal',
'pr':	'Puerto Rico',
'qa':	'Qatar',
're':	'Reunion',
'ro':	'Romania',
'ru':	'Russian Federation',
'rw':	'Rwanda',
'sh':	'Saint Helena',
'kn':	'Saint Kitts and Nevis',
'lc':	'Saint Lucia',
'pm':	'Saint Pierre and Miquelon',
'vc':	'Saint Vincent and the Grenadines',
'ws':	'Samoa',
'sm':	'San Marino',
'st':	'Sao Tome and Principe',
'sa':	'Saudi Arabia',
'sn':	'Senegal',
'rs':	'Serbia and Montenegro',
'sc':	'Seychelles',
'sl':	'Sierra Leone',
'sg':	'Singapore',
'sk':	'Slovakia',
'si':	'Slovenia',
'sb':	'Solomon Islands',
'so':	'Somalia',
'za':	'South Africa',
'gs':	'South Georgia and the South Sandwich Islands',
'es':	'Spain',
'lk':	'Sri Lanka',
'sd':	'Sudan',
'sr':	'Suriname',
'sj':	'Svalbard and Jan Mayen',
'sz':	'Swaziland',
'se':	'Sweden',
'ch':	'Switzerland',
'sy':	'Syrian Arab Republic',
'tw':	'Taiwan, Province of China',
'tj':	'Tajikistan',
'tz':	'Tanzania, United Republic of',
'th':	'Thailand',
'tl':	'Timor-Leste',
'tg':	'Togo',
'tk':	'Tokelau',
'to':	'Tonga',
'tt':	'Trinidad and Tobago',
'tn':	'Tunisia',
'tr':	'Turkey',
'tm':	'Turkmenistan',
'tc':	'Turks and Caicos Islands',
'tv':	'Tuvalu',
'ug':	'Uganda',
'ua':	'Ukraine',
'ae':	'United Arab Emirates',
'gb':	'United Kingdom',
'us':	'United States',
'um':	'United States Minor Outlying Islands',
'uy':	'Uruguay',
'uz':	'Uzbekistan',
'vu':	'Vanuatu',
've':	'Venezuela',
'vn':	'Viet Nam',
'vg':	'Virgin Islands, British',
'vi':	'Virgin Islands, U.S',
'wf':	'Wallis and Futuna',
'eh':	'Western Sahara',
'ye':	'Yemen',
'zm':	'Zambia',
'zw':	'Zimbabwe'
}

LANGUAGES_YANDEX = [
'ru',
'en',
'be',
'fr',
'de',
'id',
'kk',
'tt',
'tr',
'uk',
'uz',
'az',
'hy',
'lv',
'lt',
'et',
'ro',
'tk']

LANGUAGES_YAHOO = [
    'ar',
'bg',
'hr',
'cs',
'da',
'nl',
'en',
'et',
'fi',
'fr',
'de',
'el',
'he',
'hu',
'it',
'ja',
'ko',
'lv',
'lt',
'no',
'pl',
'pt',
'ro',
'ru',
'sk',
'sl',
'es',
'sv',
'th',
'tr',
]

COUNTRIES_YAHOO = [
    'al',
'dz',
'ar',
'am',
'au',
'at',
'az',
'bh',
'be',
'bo',
'ba',
'br',
'bg',
'ca',
'cl',
'cn',
'co',
'cr',
'hr',
'cz',
'dk',
'do',
'ec',
'eg',
'sv',
'ee',
'fi',
'mk',
'fr',
'ge',
'de',
'gr',
'gt',
'hn',
'hk',
'hu',
'is',
'in',
'id',
'ir',
'iq',
'ie',
'il',
'it',
'jp',
'jo',
'ke',
'kr',
'kw',
'lv',
'lb',
'ly',
'lt',
'lu',
'my',
'mt',
'mx',
'ma',
'nl',
'nz',
'ni',
'no',
'om',
'pk',
'pa',
'py',
'pe',
'ph',
'pl',
'pt',
'pr',
'qa',
'ro',
'ru',
'sa',
'sp',
'sg',
'sk',
'sl',
'za',
'es',
'se',
'ch',
'sy',
'tw',
'th',
'tn',
'tr',
'ae',
'ua',
'gb',
'us',
'vn',
'ye',
]

COUNTRY_LANGUAGE_DUCKDUCKGO = [
'xa-ar',
'xa-en',
'ar-es',
'au-en',
'at-de',
'be-fr',
'be-nl',
'br-pt',
'bg-bg',
'ca-en',
'ca-fr',
'ct-ca',
'cl-es',
'cn-zh',
'co-es',
'hr-hr',
'cz-cs',
'dk-da',
'ee-et',
'fi-fi',
'fr-fr',
'de-de',
'gr-el',
'hk-tzh',
'hu-hu',
'in-en',
'id-id',
'id-en',
'ie-en',
'il-he',
'it-it',
'jp-jp',
'kr-kr',
'lv-lv',
'lt-lt',
'xl-es',
'my-ms',
'my-en',
'mx-es',
'nl-nl',
'nz-en',
'no-no',
'pe-es',
'ph-en',
'ph-tl',
'pl-pl',
'pt-pt',
'ro-ro',
'ru-ru',
'sg-en',
'sk-sk',
'sl-sl',
'za-en',
'es-es',
'se-sv',
'ch-de',
'ch-fr',
'ch-it',
'tw-tzh',
'th-th',
'tr-tr',
'ua-uk',
'uk-en',
'us-en',
'ue-es',
've-es',
'vn-vi',
'wt-wt'
]

DOMAINS_GOOGLE = {'Andorra': 'google.ad',
'United Arab Emirates': 'google.ae',
'Albania': 'google.al',
'Armenia': 'google.am',
'American Samoa': 'google.as',
'Austria': 'google.at',
'Azerbaijan': 'google.az',
'Bosnia and Herzegovina': 'google.ba',
'Belgium': 'google.be',
'Burkina Faso': 'google.bf',
'Bulgaria': 'google.bg',
'Burundi': 'google.bi',
'Benin': 'google.bj',
'Bahamas': 'google.bs',
'Bhutan': 'google.bt',
'Belarus': 'google.by',
'Canada': 'google.ca',
'Democratic Republic of the Congo': 'google.cd',
'Central African Republic': 'google.cf',
'Republic of the Congo': 'google.cg',
'Switzerland': 'google.ch',
'Ivory Coast': 'google.ci',
'Chile': 'google.cl',
'Cameroon': 'google.cm',
'Angola': 'google.co.ao',
'Botswana': 'google.co.bw',
'Cook Islands': 'google.co.ck',
'Costa Rica': 'google.co.cr',
'Indonesia': 'google.co.id',
'Israel': 'google.co.il',
'India': 'google.co.in',
'Japan': 'google.co.jp',
'Kenya': 'google.co.ke',
'South Korea': 'google.co.kr',
'Lesotho': 'google.co.ls',
'Morocco': 'google.co.ma',
'Mozambique': 'google.co.mz',
'New Zealand': 'google.co.nz',
'Thailand': 'google.co.th',
'Tanzania': 'google.co.tz',
'Uganda': 'google.co.ug',
'United Kingdom': 'google.co.uk',
'Uzbekistan': 'google.co.uz',
'Venezuela': 'google.co.ve',
'United States Virgin Islands': 'google.co.vi',
'South Africa': 'google.co.za',
'Zambia': 'google.co.zm',
'Zimbabwe': 'google.co.zw',
'United States': 'google.com',
'Cape Verde': 'google.cv',
'Czech Republic': 'google.cz',
'Germany': 'google.de',
'Djibouti': 'google.dj',
'Denmark': 'google.dk',
'Dominica': 'google.dm',
'Algeria': 'google.dz',
'Estonia': 'google.ee',
'Spain': 'google.es',
'Finland': 'google.fi',
'Micronesia, Federated States of': 'google.fm',
'France': 'google.fr',
'Gabon': 'google.ga',
'Georgia': 'google.ge',
'Greenland': 'google.gl',
'Gambia': 'google.gm',
'Guadeloupe': 'google.gp',
'Greece': 'google.gr',
'Guyana': 'google.gy',
'Honduras': 'google.hn',
'Croatia': 'google.hr',
'Haiti': 'google.ht',
'Hungary': 'google.hu',
'Ireland': 'google.ie',
'Iraq': 'google.iq',
'Iceland': 'google.is',
'Italy': 'google.it',
'Jordan': 'google.jo',
'Kyrgyzstan': 'google.kg',
'Kiribati': 'google.ki',
'Kazakhstan': 'google.kz',
'Laos': 'google.la',
'Liechtenstein': 'google.li',
'Sri Lanka': 'google.lk',
'Lithuania': 'google.lt',
'Luxembourg': 'google.lu',
'Latvia': 'google.lv',
'Moldova': 'google.md',
'Madagascar': 'google.mg',
'Macedonia': 'google.mk',
'Mali': 'google.ml',
'Mongolia': 'google.mn',
'Montserrat': 'google.ms',
'Mauritius': 'google.mu',
'Maldives': 'google.mv',
'Malawi': 'google.mw',
'Niger': 'google.ne',
'Netherlands': 'google.nl',
'Norway': 'google.no',
'Nauru': 'google.nr',
'Niue': 'google.nu',
'Poland': 'google.pl',
'Palestine': 'google.ps',
'Portugal': 'google.pt',
'Romania': 'google.ro',
'Serbia': 'google.rs',
'Russia': 'google.ru',
'Rwanda': 'google.rw',
'Seychelles': 'google.sc',
'Sweden': 'google.se',
'Saint Helena, Ascension and Tristan da Cunha': 'google.sh',
'Slovenia': 'google.si',
'Slovakia': 'google.sk',
'San Marino': 'google.sm',
'Senegal': 'google.sn',
'Somalia': 'google.so',
'Suriname': 'google.sr',
'Chad': 'google.td',
'Togo': 'google.tg',
'Tokelau': 'google.tk',
'Timor-Leste': 'google.tl',
'Turkmenistan': 'google.tm',
'Tunisia': 'google.tn',
'Tonga': 'google.to',
'Trinidad and Tobago': 'google.tt',
'British Virgin Islands': 'google.vg',
'Vanuatu': 'google.vu',
'Samoa': 'google.ws',
'Afghanistan': 'google.com.af',
'Antigua and Barbuda': 'google.com.ag',
'Anguilla': 'google.com.ai',
'Argentina': 'google.com.ar',
'Australia': 'google.com.au',
'Bangladesh': 'google.com.bd',
'Bahrain': 'google.com.bh',
'Brunei': 'google.com.bn',
'Bolivia': 'google.com.bo',
'Brazil': 'google.com.br',
'Belize': 'google.com.bz',
'Colombia': 'google.com.co',
'Cuba': 'google.com.cu',
'Cyprus': 'google.com.cy',
'Dominican Republic': 'google.com.do',
'Ecuador': 'google.com.ec',
'Egypt': 'google.com.eg',
'Ethiopia': 'google.com.et',
'Fiji': 'google.com.fj',
'Ghana': 'google.com.gh',
'Gibraltar': 'google.com.gi',
'Guatemala': 'google.com.gt',
'Hong Kong': 'google.com.hk',
'Jamaica': 'google.com.jm',
'Cambodia': 'google.com.kh',
'Kuwait': 'google.com.kw',
'Lebanon': 'google.com.lb',
'Libya': 'google.com.ly',
'Myanmar': 'google.com.mm',
'Malta': 'google.com.mt',
'Mexico': 'google.com.mx',
'Malaysia': 'google.com.my',
'Namibia': 'google.com.na',
'Nigeria': 'google.com.ng',
'Nicaragua': 'google.com.ni',
'Nepal': 'google.com.np',
'Oman': 'google.com.om',
'Panama': 'google.com.pa',
'Peru': 'google.com.pe',
'Papua New Guinea': 'google.com.pg',
'Philippines': 'google.com.ph',
'Pakistan': 'google.com.pk',
'Puerto Rico': 'google.com.pr',
'Paraguay': 'google.com.py',
'Qatar': 'google.com.qa',
'Saudi  Arabia': 'google.com.sa',
'Solomon Islands': 'google.com.sb',
'Singapore': 'google.com.sg',
'Sierra Leone': 'google.com.sl',
'El Salvador': 'google.com.sv',
'Tajikistan': 'google.com.tj',
'Turkey': 'google.com.tr',
'Taiwan': 'google.com.tw',
'Ukraine': 'google.com.ua',
'Uruguay': 'google.com.uy',
'Saint Vincent and the Grenadines': 'google.com.vc',
'Vietnam': 'google.com.vn'
}

INDICATOR_METADATA = {
  "1-cert-domain": {
    "name": "Domain Certificate",
    "description": "An SSL certificate is a digital certificate that authenticates a website's or multiple websites' identity and enables an encrypted connection.",
    "interpretation": "A shared certificate between two sites is strong evidence of a link between sites, as typically a certificate must be issued for all those sites at once by a single entity and cannot easily be spoofed. However, some web hosting and DDOS protection services bundle certificates for unrelated sites, so carefully research any matches."
  },
  "1-crypto-wallet": {
    "name": "Cryptocurrency Wallet",
    "description": "A digital wallet used to store, send, and receive cryptocurrencies like Bitcoin and Ethereum.",
    "interpretation": "The presence of a cryptocurrency wallet address can link a site or an individual to cryptocurrency transactions, potentially indicating financial sources or preferences. However, due to the pseudonymous nature of such wallets, additional information is required to definitively establish ownership or connections."
  },
  "1-domain": {
    "name": "Domain Name",
    "description": "The unique name that identifies a website, which is registered in the Domain Name System (DNS).",
    "interpretation": "The domain name can provide insights into the nature or origin of a website. Commonalities in domain names may suggest shared affiliations or intents. However, the ease of registering domain names requires careful analysis to avoid false associations."
  },
  "1-domain_suffix": {
    "name": "Domain Suffix",
    "description": "The last part of a domain name, typically representing a category or country code.",
    "interpretation": "A domain suffix can indicate the intended audience or origin of a website. Similar suffixes across different sites might suggest a geographical or organizational link. Yet, the global accessibility of most suffixes means this should not be a sole determinant of connection."
  },
  "1-fb_pixel_id": {
    "name": "Facebook Pixel ID",
    "description": "A unique identifier for the Facebook Pixel, an analytics tool that allows website owners to measure the effectiveness of their advertising by understanding the actions people take on their website.",
    "interpretation": "Shared Facebook Pixel IDs across sites can indicate common ownership or a shared marketing strategy. However, third-party marketing agencies might use the same ID across different clients, potentially leading to mistaken connections."
  },
  "1-adobe_analytics_id": {
    "name": "Adobe Analytics ID",
    "description": "A unique identifier used by Adobe Analytics, a tool for analyzing visitor traffic on websites.",
    "interpretation": "Similar to other analytics tools, shared Adobe Analytics IDs can hint at common management or partnerships between websites. However, as with Facebook Pixel IDs, the use of analytics IDs by third-party services may introduce unrelated links."
  },
  "3-sitemap_entries": {
    "name": "Sitemap Entries",
    "description": "Entries in a website's sitemap, which is an XML file listing the URLs for a site along with additional metadata about each URL.",
    "interpretation": "Analysis of sitemap entries can reveal the structure and content priorities of a website. Commonalities in sitemap structures or content might suggest shared authorship or objectives. However, similarities could also result from common website templates or platforms."
  },
  "3-ipms_domain_iprangeowner_cidr": {
    "name": "IP Range Owner CIDR",
    "description": "The Classless Inter-Domain Routing (CIDR) notation indicating the range of IP addresses owned by an entity.",
    "interpretation": "CIDR data can help identify the network scope and location of a domain's hosting. Shared IP ranges might suggest hosting or service provider commonalities. However, large hosting providers may have numerous unrelated clients within the same range."
  },
  "3-ipms_domain_iprangeowner_ownerName": {
    "name": "IP Range Owner Name",
    "description": "The name of the entity owning a range of IP addresses.",
    "interpretation": "This information can be used to identify the hosting provider or organization controlling a set of IP addresses. Shared ownership names might indicate a relationship between the entities using those IPs, though large organizations often host unrelated entities."
  },
  "3-ipms_domain_iprangeowner_address": {
    "name": "IP Range Owner Address",
    "description": "Physical address of the entity owning a range of IP addresses.",
    "interpretation": "Physical addresses can provide geographical and organizational context. Shared addresses across different IP ranges might suggest a close relationship or common management. However, the presence of data centers and shared office spaces can result in address overlaps for unrelated entities."
  },
  "3-ipms_domain_nameserver": {
    "name": "Domain Name Server",
    "description": "A server that translates domain names into IP addresses, facilitating the connection between a user's device and the website's server.",
    "interpretation": "Common nameservers among different domains might indicate shared hosting or management services. However, popular hosting providers serve a large number of clients, potentially leading to false associations."
  },
  "3-ipms_domain_otheripused": {
    "name": "Other IPs Used by Domain",
    "description": "A list of IP addresses that have been used by a domain, aside from its primary IP address.",
    "interpretation": "This data can reveal the network history and changes in hosting of a domain. Shared historical IPs might suggest past commonalities or transitions in hosting services. However, dynamic IP allocation by hosting services can result in unrelated sites temporarily sharing IPs."
  },
  "3-ipms_siteonthisip_now": {
    "name": "Current Sites on This IP",
    "description": "Websites currently hosted on the same IP address.",
    "interpretation": "Websites sharing an IP address may have a relationship, such as being part of the same network or organization. However, shared hosting environments can lead to unrelated websites being hosted on the same IP."
  },
  "3-ipms_siteonthisip_before": {
    "name": "Former Sites on This IP",
    "description": "Websites that were previously hosted on the same IP address but are no longer.",
    "interpretation": "Historical data on IP hosting can provide insights into the network associations and changes over time. Formerly shared IPs might indicate previous relationships or common hosting decisions. However, dynamic IP allocations can lead to brief and incidental overlaps."
  },
  "3-ipms_siteonthisip_broken": {
    "name": "Broken Sites on This IP",
    "description": "Websites hosted on the same IP address that are currently not functional or accessible.",
    "interpretation": "Identifying non-functional sites on a shared IP can indicate network health or hosting issues. Patterns in broken sites might suggest targeted disruptions or poor hosting services. However, temporary technical issues can also cause sites to be non-functional, unrelated to their network neighbors."
  },
  "3-ipms_useragents": {
    "name": "User Agents",
    "description": "Strings that web browsers and other client devices send to identify themselves to web servers, typically containing information about the device and browser.",
    "interpretation": "Analysis of user agents can reveal the types of devices and browsers most frequently accessing a site, potentially indicating the site's target audience or technological preferences. However, the widespread use of common browsers can limit the specificity of these insights."
  },
  "1-ip_shodan_hostnames": {
    "name": "Shodan Hostnames",
    "description": "Hostnames associated with an IP address as indexed by Shodan, a search engine for internet-connected devices.",
    "interpretation": "Shodan's data can reveal the various services and hostnames associated with an IP, potentially indicating its use and ownership. Shared hostnames across IPs might suggest network or organizational links. However, the dynamic nature of IP allocations can lead to transient or outdated hostname associations."
  },
  "3-ip_shodan_ports": {
    "name": "Shodan Ports",
    "description": "Open network ports on an IP address as detected by Shodan.",
    "interpretation": "Open ports can indicate the types of services an IP is offering, with certain ports associated with specific applications or protocols. Common ports across different IPs might suggest similar uses or configurations. However, standard port uses can be widespread and not necessarily indicative of direct relationships."
  },
  "2-ip_shodan_vuln": {
    "name": "Shodan Vulnerabilities",
    "description": "Vulnerabilities identified on an IP address by Shodan, based on open ports and services.",
    "interpretation": "Identifying vulnerabilities can help assess the security posture of a network or device. Shared vulnerabilities might indicate common software or configuration weaknesses. However, widespread vulnerabilities in popular software can appear across unrelated networks."
  },
  "3-ip_shodan_cpe": {
    "name": "Shodan CPE",
    "description": "Common Platform Enumeration (CPE) identifiers found by Shodan, indicating specific software or hardware on an IP.",
    "interpretation": "CPE identifiers can provide detailed insights into the technological stack of a network or device. Shared CPEs might suggest technological commonalities or shared suppliers. However, the ubiquity of certain technologies can lead to coincidental overlaps."
  },
  "1-ga_id": {
    "name": "Google Analytics ID",
    "description": "A unique identifier associated with Google Analytics, used for tracking and analyzing website traffic.",
    "interpretation": "Like other analytics IDs, shared Google Analytics IDs across websites may indicate common ownership or marketing strategies. However, the use of third-party marketing agencies can result in the same ID being used across unrelated sites."
  },
  "1-ga_tag_id": {
    "name": "Google Analytics Tag ID",
    "description": "A unique tag identifier used in Google Analytics for tracking specific user interactions on a website.",
    "interpretation": "Similar to the general Google Analytics ID, shared tag IDs might suggest a connection between sites, especially in how they track user behavior. However, similar tracking strategies might also be independently adopted by unrelated sites."
  },
  "1-ip": {
    "name": "IP Address",
    "description": "A unique numerical label assigned to each device connected to a computer network that uses the Internet Protocol for communication.",
    "interpretation": "An IP address can reveal the geographic location and network provider of a device or website. Shared IPs may indicate shared hosting or network resources. However, dynamic IP allocation and large hosting environments can lead to incidental sharing."
  },
  "1-verification_id": {
    "name": "Verification ID",
    "description": "A unique identifier used for verifying ownership or authenticity of a website or online account.",
    "interpretation": "Verification IDs can establish the legitimacy of a site or account, potentially linking it to a specific owner or organization. However, verification processes vary, and IDs can be reassigned or spoofed, requiring careful verification."
  },
  "1-yandex_tag_id": {
    "name": "Yandex Tag ID",
    "description": "A unique identifier used by Yandex Metrica, a tool for analyzing visitor traffic, similar to Google Analytics.",
    "interpretation": "Shared Yandex Tag IDs could suggest common ownership or similar web analytics strategies between sites. However, like other analytics tools, the involvement of third-party services can create misleading connections."
  },
  "2-subnet": {
    "name": "Subnet",
    "description": "A segment of a network's IP address range that can be designated to optimize performance and security.",
    "interpretation": "Subnet information can indicate how a network is structured and segmented for various purposes. Shared subnets between different entities might suggest a relationship or common network management. However, subnets are often allocated by ISPs or hosting providers to multiple clients."
  },
  "3-cdn-domain": {
    "name": "CDN Domain",
    "description": "A domain used by a Content Delivery Network (CDN) to deliver content efficiently across the internet.",
    "interpretation": "Shared CDN domains can indicate that websites are utilizing the same CDN provider for content distribution, which might imply performance or operational preferences. However, popular CDNs are used by a wide range of websites, limiting the value of this data for establishing direct connections."
  },
  "3-cms": {
    "name": "Content Management System",
    "description": "A software application or set of related programs used to create and manage digital content.",
    "interpretation": "Common CMS platforms among different websites might suggest similar operational needs or preferences. However, widely-used CMS platforms like WordPress are employed by a diverse array of sites, often without any direct relation."
  },
  "3-css_classes": {
    "name": "CSS Classes",
    "description": "Classes defined in Cascading Style Sheets (CSS) to style and format the layout of web pages.",
    "interpretation": "Analysis of CSS classes can provide insights into the design and development approaches of a website. Shared classes might suggest common design templates or developers. However, common frameworks and libraries can lead to similar CSS classes across unrelated sites."
  },
  "3-header-nonstd-value": {
    "name": "Non-Standard Header Value",
    "description": "Values in HTTP headers that do not conform to standard header formats, potentially indicating custom configurations or software.",
    "interpretation": "Non-standard header values can be unique identifiers of custom configurations or software used by a website. Shared non-standard values might indicate common development practices or software choices. However, the interpretation of these values requires technical expertise to avoid misattribution."
  },
  "3-header-server": {
    "name": "Server Header",
    "description": "The 'Server' HTTP header field that specifies information about the software used by the origin server.",
    "interpretation": "The server header can reveal the web server software and its configuration. Shared server headers might indicate similar technological choices or configurations. However, popular server software like Apache and Nginx is widely used, so this data alone is not sufficient to establish a connection."
  },
  "3-id_tags": {
    "name": "ID Tags",
    "description": "Unique identifiers used in the HTML code of a website to distinguish specific elements.",
    "interpretation": "Similar ID tags across websites might suggest shared development practices or template usage. However, common ID tags can also be a result of widespread frameworks or libraries, and thus, might not be indicative of direct relationships."
    },
    "3-iframe_id_tags": {
    "name": "Iframe ID Tags",
    "description": "Unique identifiers used for 'iframe' elements in HTML, allowing the embedding of an external webpage within a webpage.",
    "interpretation": "Shared Iframe ID tags could indicate similar website functionalities or content sharing strategies. However, common frameworks or website templates can lead to the usage of similar Iframe IDs across different websites, reducing the significance of this correlation."
    },
    "3-link_href": {
    "name": "Link Href Attributes",
    "description": "The 'href' attribute of a link in HTML, specifying the URL of the page the link goes to.",
    "interpretation": "Analysis of 'href' attributes can reveal the external connections or references a website makes. Shared 'href' attributes across different sites might suggest common affiliations or sources. However, links to popular or general websites might not be indicative of a direct relationship."
    },
    "3-meta_generic": {
    "name": "Generic Meta Tags",
    "description": "Meta tags in HTML that provide general information about a webpage, such as description, keywords, and author.",
    "interpretation": "Common meta tags can indicate similar content or objectives. However, generic or broadly used tags may appear in a wide range of websites, potentially leading to mistaken connections."
    },
    "3-meta_social": {
    "name": "Social Media Meta Tags",
    "description": "Meta tags specifically designed for optimizing social media sharing, defining how content appears when shared on social platforms.",
    "interpretation": "Shared social media meta tags might suggest a coordinated approach to social media engagement or content strategy. However, the use of standard social media optimization practices can lead to similar tags across unrelated sites."
    },
    "3-script_src": {
    "name": "Script Source Attributes",
    "description": "The 'src' attribute of a script tag in HTML, indicating the source of a JavaScript file.",
    "interpretation": "Shared script sources can point to the use of common libraries or external scripts. However, the widespread use of popular JavaScript libraries and scripts might lead to coincidental similarities."
    },
    "3-uuid": {
    "name": "UUID",
    "description": "Universally Unique Identifier, a 128-bit number used to identify information in computer systems.",
    "interpretation": "UUIDs can be used to track and manage assets or components within a system. Shared UUIDs might indicate a connection between different systems or components. However, the nature of UUIDs as unique identifiers typically limits the occurrence of shared UUIDs across unrelated systems."
    },
    "3-whois_creation_date": {
    "name": "WHOIS Creation Date",
    "description": "The date a domain name was first registered, as recorded in the WHOIS database.",
    "interpretation": "Similar creation dates for domains might suggest a coordinated launch or common origin. However, coincidental registration dates are possible, especially during popular events or domain sales."
    },
    "3-whois_server": {
    "name": "WHOIS Server",
    "description": "The server that provides the WHOIS information, containing details about domain name registrations.",
    "interpretation": "Use of the same WHOIS server for different domains could indicate a preference for certain domain registrars. However, popular registrars serve a large number of clients, so this alone isn't a strong indicator of a relationship."
    },
    "3-whois-registrar": {
    "name": "WHOIS Registrar",
    "description": "The organization authorized to register and manage domain names for a particular top-level domain.",
    "interpretation": "Domains registered through the same registrar might have some administrative commonalities. However, given the market dominance of certain registrars, this is not a definitive sign of a direct connection between domain owners."
    },
    "3-wp-blocks": {
    "name": "WordPress Blocks",
    "description": "Content blocks used in WordPress to build and design webpages.",
    "interpretation": "Shared WordPress blocks could indicate similar website designs or use of common templates. However, due to the popularity of WordPress and its wide range of available blocks, similarities might occur coincidentally."
    },
    "3-wp-categories": {
    "name": "WordPress Categories",
    "description": "Categorization system in WordPress used to group content into different sections.",
    "interpretation": "Similar categories in different WordPress sites might suggest related content or thematic similarities. However, common categories are widely used across various sites, potentially leading to non-significant matches."
    },
    "3-wp-pages": {
    "name": "WordPress Pages",
    "description": "Web pages created and managed within the WordPress platform.",
    "interpretation": "Analysis of WordPress pages can reveal the structure and content emphasis of a site. Shared page structures or content might suggest a common template or designer. However, the extensive use of WordPress templates can lead to similar page structures across unrelated sites."
    },
    "3-wp-posts": {
    "name": "WordPress Posts",
    "description": "Blog posts or articles published on a WordPress website.",
    "interpretation": "Shared themes or styles in WordPress posts might indicate similar content strategies or sources. However, the widespread use of WordPress for blogging and content creation means that thematic overlaps are common and not necessarily indicative of a connection."
    },
    "3-wp-tags": {
    "name": "WordPress Tags",
    "description": "Tagging system in WordPress used to describe specific details of posts, aiding in content organization and navigation.",
    "interpretation": "Common tags across WordPress sites might suggest related topics or a shared content approach. However, popular tags are frequently used across diverse websites, diminishing the potential for meaningful connections."
    },
    "3-wp-users": {
    "name": "WordPress Users",
    "description": "Individual accounts within WordPress that have various roles and permissions for managing website content.",
    "interpretation": "Shared user accounts or roles across WordPress sites might imply common administration or authorship. However, generic user roles such as 'administrator' or 'editor' are common and not uniquely identifying."
    },
    "2-urlscan_globalvariable": {
    "name": "URLScan Global Variable",
    "description": "Global JavaScript variables identified by URLScan, a tool for scanning and analyzing websites.",
    "interpretation": "Shared global variables might indicate the use of similar scripts or frameworks. However, common JavaScript practices and libraries can result in widespread use of the same global variables across different websites."
    },
    "2-urlscan_cookies": {
    "name": "URLScan Cookies",
    "description": "Cookies identified by URLScan as being set by websites during a scan.",
    "interpretation": "Analysis of cookies can reveal tracking, personalization, or functional aspects of a website. Shared cookies across sites might suggest shared tracking or management tools. However, common third-party services, like analytics or advertising platforms, often set similar cookies across various websites."
    },
    "2-urlscan_consolemessages": {
    "name": "URLScan Console Messages",
    "description": "Messages output to the browser console during a website scan by URLScan.",
    "interpretation": "Console messages can provide insights into the website's functionality or potential issues. Common messages across different scans might indicate similar development practices or shared issues. However, these messages can also be generated by common frameworks or browser extensions."
    },
    "2-urlscan_asn": {
    "name": "URLScan Autonomous System Number",
    "description": "The Autonomous System Number (ASN) identified by URLScan, representing the collection of IP networks and routers under the control of one entity.",
    "interpretation": "Shared ASNs can suggest that websites are part of the same network or hosted by the same provider. However, large hosting providers and ISPs control extensive ASNs that encompass a wide range of clients."
    },
    "2-urlscan_domainsonpage": {
    "name": "URLScan Domains on Page",
    "description": "A list of all domains found on a webpage during a URLScan.",
    "interpretation": "Domains listed on a page can reveal external links or embedded content. Shared domains across different webpages might suggest common affiliations or sources. However, widely used domains, such as social media or analytics platforms, are commonly found across numerous sites."
    },
    "2-urlscan_urlssonpage": {
    "name": "URLScan URLs on Page",
    "description": "All URLs found on a webpage during a URLScan.",
    "interpretation": "The presence of specific URLs can indicate the nature of the content or the external connections of a website. Shared URLs across different pages might suggest a relationship or common sources. However, links to popular websites or resources might not be uniquely significant."
    },
    "2-urlscanhrefs": {
    "name": "URLScan Hrefs",
    "description": "Hypertext references (hrefs) identified on webpages during a URLScan.",
    "interpretation": "Href attributes can provide insights into the external links and relationships of a website. Common hrefs across different sites might suggest shared affiliations or content. However, links to widely used resources or platforms can appear across many sites, limiting the potential for direct connection inference."
    },
    "2-techstack": {
    "name": "Technology Stack",
    "description": "The set of technologies used to build and run a website or application, including frameworks, languages, and software.",
    "interpretation": "Similar technology stacks can suggest shared development practices or preferences. However, certain technology combinations are widely popular and may be used by a vast range of unrelated websites or applications."
    },
    "2-ads_txt": {
    "name": "Ads.txt File",
    "description": "An ads.txt file is an initiative by the Interactive Advertising Bureau (IAB) to increase transparency in programmatic advertising by allowing publishers to list authorized digital sellers of their inventory.",
    "interpretation": "Shared ads.txt files can indicate common advertising partners or monetization strategies. However, the use of third-party ad networks and resellers can lead to shared ads.txt entries across unrelated websites."
    },
    "3-footer-text": {
    "name": "Footer Text",
    "description": "Text content found in the footer section of a webpage.",
    "interpretation": "Analysis of footer text can provide insights into the website's branding, copyright information, or contact details. Shared footer text might suggest common design elements or template usage. However, generic or widely used footer text can appear across diverse websites."
    },
    "4-outbound-domain": {
    "name": "Outbound Domain",
    "description": "A domain to which a website links or redirects its users.",
    "interpretation": "Shared outbound domains can indicate common affiliations or content sources. However, links to popular websites or services can appear across a wide range of unrelated sites, limiting the significance of this data for direct connections."
    },
    '3-twitter': {
    "name": "Twitter Link",
    "description": "A link to a Twitter profile or tweet found on a webpage.",
    "interpretation": "Links to Twitter profiles or tweets can indicate social media engagement or content sharing strategies. Shared Twitter links might suggest common social media strategies or affiliations. However, links to popular social media platforms are widely used and may not be uniquely significant."
    },
    '3-facebook': {
    "name": "Facebook Link",
    "description": "A link to a Facebook page or post found on a webpage.",
    "interpretation": "Links to Facebook pages or posts can indicate social media engagement or content sharing strategies. Shared Facebook links might suggest common social media strategies or affiliations. However, links to popular social media platforms are widely used and may not be uniquely significant."
    },
    '3-youtube': {  
    "name": "YouTube Link",
    "description": "A link to a YouTube channel or video found on a webpage.",
    "interpretation": "Links to YouTube channels or videos can indicate content sharing or promotional strategies. Shared YouTube links might suggest common content sources or affiliations. However, links to popular video platforms are widely used and may not be uniquely significant."
    },
    '3-telegram': {
    "name": "Telegram Link",
    "description": "A link to a Telegram channel or post found on a webpage.",
    "interpretation": "Links to Telegram channels or posts can indicate content sharing or promotional strategies. Shared Telegram links might suggest common content sources or affiliations. However, links to popular messaging platforms are widely used and may not be uniquely significant."
    },
    '3-outbound-domain': {
    "name": "Outbound Domain",
    "description": "A domain to which a website links or redirects its users.",
    "interpretation": "Shared outbound domains can indicate common affiliations or content sources. However, links to popular websites or services can appear across a wide range of unrelated sites, limiting the significance of this data for direct connections."
    },
    '3-patreon': {
    "name": "Patreon Link",
    "description": "A link to a Patreon page or post found on a webpage.",
    "interpretation": "Links to Patreon pages or posts can indicate content sharing or promotional strategies. Shared Patreon links might suggest common content sources or affiliations. However, links to crowdfunding platforms are widely used and may not be uniquely significant."
    },
    '3-gab' : {
    "name": "Gab Link",
    "description": "A link to a Gab profile or post found on a webpage.",
    "interpretation": "Links to Gab profiles or posts can indicate social media engagement or content sharing strategies. Shared Gab links might suggest common social media strategies or affiliations. However, links to alternative social media platforms are widely used and may not be uniquely significant."
    }


}

MATCH_VALUES_TO_IGNORE = [
    'X-Powered-By:Express',
    '[]',
    '1e024a78.js',
    'og:type|website',
    'twitter:card|summary_large_image',
    'set()',
    'gpt.js',
    '[80, 443]',
    'viewport|width=device-width, initial-scale=1',
    'www.facebook.com',
    '[22, 80, 443]',
    'adsbygoogle.js',
    'csrf-param|authenticity_token',
    'viewport|width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=0',
    'viewport|width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0, shrink-to-fit=no',
    'google-site-verification|',
    'fb:pages|',
    'locallabs.com',
    's3.amazonaws.com',
    'px.ads.linkedin.com',
    'og:locale|en_US',
    'robots|max-image-preview:large',
    'rocket-loader.min.js',
    'jquery.min.js',
    'mc.yandex.ru',
    'og:locale|ar_AR',
    'sni.cloudflaressl.com',
    'theme-color|#ffffff',
    'bootstrap.min.js',
    'context.js',
    'og:image:width|1200',
    'jquery-migrate.min.js',
    'cdnjs.cloudflare.com',
    'robots|index, follow',
    'og:image:type|image/png',
    'og:image:type|image/jpeg',
    'viewport|width=device-width, initial-scale=1, shrink-to-fit=no',
    'apple-mobile-web-app-capable|yes',
    'og:locale|ru_RU',
    'format-detection|telephone=no',
    'viewport|width=device-width, initial-scale=1.0, shrink-to-fit=yes',
    'sni.cloudflaressl.com',
    'HandheldFriendly|true',
    'e-202402.js',
    'i0.wp.com',
    'e-202401.js',
    'platform.js',
    'onesignal|wordpress-plugin',
    'loader.js',
    'script.js',
    'og:image:height|630',
    'robots|index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1',
    'og:locale|en_GB',
    'viewport|width=device-width,minimum-scale=1,initial-scale=1',
    'viewport|width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no',
    'pages',
    []

]

LEAD_GEN_INDICATORS = [
    '2-ads_txt',
    '4-outbound-domain',
    '3-cdn-domain',
    '3-meta_generic'
]