"""consolidate sites tables

Revision ID: ac136f05f60d
Revises: 
Create Date: 2024-05-17 14:30:17.109273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac136f05f60d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_sites')
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_base', sa.Boolean(), nullable=True))
        batch_op.drop_column('from_user')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('from_user', sa.BOOLEAN(), nullable=False))
        batch_op.drop_column('is_base')

    op.create_table('_alembic_tmp_sites',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('is_base', sa.BOOLEAN(), nullable=False),
    sa.Column('created', sa.DATETIME(), nullable=True),
    sa.Column('updated', sa.DATETIME(), nullable=True),
    sa.Column('domain', sa.VARCHAR(length=100), nullable=False),
    sa.Column('source', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
