FINANCIAL_IDS = {
    # Donation/Pledge
    'patreon': {'tier': 3, 'pattern': r'https?:\/\/(?:www\.)patreon\.com\/[a-zA-Z0-9_]+'},
    'ko-fi': {'tier': 3, 'pattern': r'https?:\/\/(?:www\.)ko-fi\.com\/[a-zA-Z0-9_]+'},
    'buymeacoffee': {'tier': 3, 'pattern': r'https?:\/\/(?:www\.)buymeacoffee\.com\/[a-zA-Z0-9_]+'},
    'indigogo': {'tier': 3, 'pattern': r'https?:\/\/(?:www\.)indiegogo\.com\/individuals\/[0-9]+\/[a-zA-Z0-9_-]+'},
    'kickstarter': {'tier': 3, 'pattern': r'https?:\/\/(?:www\.)kickstarter\.com\/projects\/[a-zA-Z0-9_]+\/[a-zA-Z0-9_-]+'},
    'gofundme': {'tier': 3, 'pattern': r'https?:\/\/(?:www\.)gofundme\.com\/f\/[a-zA-Z0-9_-]+'},
    'seed&spark': {'tier': 3, 'pattern': r'https?:\/\/(?:www\.)seedandspark\.com\/fund\/[a-zA-Z0-9_-]+'},
    'substack': {'tier': 3, 'pattern': r'https?:\/\/[a-zA-Z0-9_-]+\.substack\.com'},
    'gumroad': {'tier': 3, 'pattern': r'https?:\/\/(?:www\.)gumroad\.com\/[a-zA-Z0-9_-]+'},
    'podia': {'tier': 3, 'pattern': r'https?:\/\/[a-zA-Z0-9_-]+\.podia\.com'},
    'steady': {'tier': 3, 'pattern': r'https?:\/\/(?:www\.)steadyhq\.com\/en\/[a-zA-Z0-9_-]+'},
    'itchio': {'tier': 3, 'pattern': r'https?:\/\/[a-zA-Z0-9_-]+\.itch\.io'},
    'tiltify': {'tier': 3, 'pattern': r'https?:\/\/(?:www\.)tiltify\.com\/@[a-zA-Z0-9_-]+'},
    'fundly': {'tier': 3, 'pattern': r'https?:\/\/(?:www\.)fundly\.com\/[a-zA-Z0-9_-]+'},
    'mightycause': {'tier': 3, 'pattern': r'https?:\/\/(?:www\.)mightycause\.com\/story\/[a-zA-Z0-9_-]+'},
    'onlyfans': {'tier': 3, 'pattern': r'https?:\/\/(?:www\.)onlyfans\.com\/[a-zA-Z0-9_-]+'},
    'donorbox': {'tier': 3, 'pattern': r'https?:\/\/(?:www\.)donorbox\.org\/(?:embed\/)?[a-zA-Z0-9_\-?&=.]+'},
    'stripe-donate': {'tier': 3, 'pattern': r'https?:\/\/donate.stripe.com\/[a-zA-Z0-9]+'},
    # Store/Retail
    'zazzle': {'tier': 3, 'pattern': r'https?:\/\/(?:www\.)zazzle\.com\/[a-zA-Z0-9_\-\/]+'},
    'cafepress': {'tier': 3, 'pattern': r'https?:\/\/(?:www\.)cafepress\.com\/[a-zA-Z0-9_\-\.\/]+'},
    'shopify': {'tier': 3, 'pattern': r'https?:\/\/[a-zA-Z0-9-]+.myshopify.com'},
    # Affiliate links
    'amazonassociate': {'tier': 3, 'pattern': r'https?:\/\/(?:www\.)amazon\.com\/(?:dp|gp\/product)\/[A-Z0-9]+\/ref=nosim\?tag=([a-zA-Z0-9_-]+)'},
    'ebaypartner': {'tier': 3, 'pattern': r'https?:\/\/rover\.ebay\.com\/rover\/1\/[0-9]+-[0-9]+-[0-9]+-[0-9]+\/[0-9]\?mpre=https?%3A%2F%2F(?:www\.)ebay\.com%2Fulk%2Fitm%2F([0-9]+)'},
    'shareasale': {'tier': 3, 'pattern': r'https?:\/\/(?:www\.)shareasale\.com\/r\.cfm\?b=[0-9]+&u=([0-9]+)&m=[0-9]+&urllink=&afftrack='},
    'clickbank': {'tier': 3, 'pattern': r'https?:\/\/[a-zA-Z0-9_-]+\.hop\.clickbank\.net\/\?tid=([A-Z0-9]+)'},
    'commissionjunction': {'tier': 3, 'pattern': r'https?:\/\/(?:www\.)anrdoezrs\.net\/links\/[0-9]+\/type\/dlg\/sid\/([a-zA-Z0-9_-]+)\/'},
    'rakutenmarketing': {'tier': 3, 'pattern': r'https?:\/\/click\.linksynergy\.com\/fs-bin\/click\?id=([a-zA-Z0-9]+)&offerid='},
    'impactaffiliate': {'tier': 3, 'pattern': r'https?:\/\/app\.impact\.com\/secure\/brand\/bfo\.go\?id=([a-zA-Z0-9_-]+)'},
    'awin': {'tier': 3, 'pattern': r'https?:\/\/(?:www\.)awin1\.com\/cread\.php\?awinmid=[0-9]+&awinaffid=([0-9]+)&clickref='},
    'bluehostaffiliate': {'tier': 3, 'pattern': r'https?:\/\/(?:www\.)bluehost\.com\/track\/([a-zA-Z0-9_-]+)/'},
    'shopifyaffiliate': {'tier': 3, 'pattern': r'https?:\/\/(?:www\.)shopify\.com\/?ref=([a-zA-Z0-9_-]+)'},
    'hostgatoraffiliate': {'tier': 3, 'pattern': r'https?:\/\/secure\.hostgator\.com\/~affiliat\/cgi-bin\/affiliates\/clickthru\.cgi\?id=([a-zA-Z0-9_-]+)'},
    'wixaffiliate': {'tier': 3, 'pattern': r'https?:\/\/wix\.com\/?utm_campaign=vir_affiliate&ref=([a-zA-Z0-9_]+)'},
    'sitegroundaffiliate': {'tier': 3, 'pattern': r'https?:\/\/(?:www\.)siteground\.com\/index\.htm\?afcode=([a-zA-Z0-9_]+)'},
    'adobeaffiliate': {'tier': 3, 'pattern': r'https?:\/\/(?:www\.)adobe\.com\/?sdid=([a-zA-Z0-9]+)'},
    'semrushaffiliate': {'tier': 3, 'pattern': r'https?:\/\/(?:www\.)semrush\.com\/?ref=([a-zA-Z0-9]+)'},
    'fiverraffiliate': {'tier': 3, 'pattern': r'https?:\/\/track\.fiverr\.com\/visit\/\?bta=([0-9]+)&brand=fiverrcpa'},
    'maxbounty': {'tier': 3, 'pattern': r'https?:\/\/(?:www\.)maxbounty\.com\/?aff_id=([0-9]+)'},
    'flexoffers': {'tier': 3, 'pattern': r'https?:\/\/(?:www\.)flexoffers\.com\/AffiliatePrograms\/?referrer=([0-9]+)'},
    'viglink': {'tier': 3, 'pattern': r'https?:\/\/outbound\.viglink\.com\/\?key=([a-zA-Z0-9]+)&u='},
    'skimlinks': {'tier': 3, 'pattern': r'https?:\/\/go\.skimresources\.com\/\?id=([0-9]+)&xs=1&url='},
    'targetaffiliate': {'tier': 3, 'pattern': r'https?:\/\/goto\.target\.com\/c\/[0-9]+\/[0-9]+\/[0-9]+\?a=([a-zA-Z0-9_]+)&sm='},
    'walmartaffiliate': {'tier': 3, 'pattern': r'https?:\/\/linksynergy\.walmart\.com\/deeplink\?id=([a-zA-Z0-9]+)&murl='},
    # ads
    "doubleclick_ads": {'tier': 3, 'pattern': r"https:\/\/googleads\.g\.doubleclick\.net\/pagead\/ads\?.*?client=(ca-pub-\d+)"},
    "google_ads": {'tier': 3, 'pattern': r"https:\/\/www\.google\..*?\/aclk\?.*?adurl=(https:\/\/.*?)&"},
    "facebook_ads": {'tier': 3, 'pattern': r"https:\/\/www\.facebook\.com\/.*?\/ads\/.*?\?id=(\d+)"},
    "amazon_advertising_ads": {'tier': 3, 'pattern': r"https:\/\/aax\.amazon-adsystem\.com\/.*?&adInstanceId=(\w+)"},
    "microsoft_advertising_ads": {'tier': 3, 'pattern': r"https:\/\/(.*?)\.r\.msn\.com\/.*?\?adid=(\d+)",
    "google_adservices_ads": {'tier': 3, 'pattern': r"https:\/\/www\.google\.com\/adservices\/.*?pagead\/aclk\?.*?sa=L&ai=(.*?)&"},
    "appnexus_ads": {'tier': 3, 'pattern': r"https:\/\/ib\.adnxs\.com\/.*?\?id=(\d+)"},
    "criteo_ads": {'tier': 3, 'pattern': r"https:\/\/gum\.criteo\.com\/.*?&adid=(\w+)"},
    "taboola_ads": {'tier': 3, 'pattern': r"https:\/\/trc\.taboola\.com\/.*?libId=(\w+)"},
    "rubicon_ads": {'tier': 3, 'pattern': r"https:\/\/optimized-by\.rubiconproject\.com\/.*?&account_id=(\d+)"},
    "openx_ads": {'tier': 3, 'pattern': r"https:\/\/(.*?)\.servedbyopenx\.com\/.*?&auid=(\d+)"},
    "smart adserver_ads": {'tier': 3, 'pattern': r"https:\/\/(.*?)\.smartadserver\.com\/.*?&tagId=(\d+)"},
    "adform_ads": {'tier': 3, 'pattern': r"https:\/\/track\.adform\.net\/.*?&adid=(\d+)"},
    "smaato_ads": {'tier': 3, 'pattern': r"https:\/\/smaato\.com\/.*?&adSpaceId=(\d+)"},
    "linkedin ads_ads": {'tier': 3, 'pattern': r"https:\/\/www\.linkedin\.com\/ads\/.*?id=(\d+)"}

