FEATURE_MATCHING: dict[str, str] = {
"1-cert-domain" : "direct",
"1-crypto-wallet" : "direct",
"1-domain" : "direct",
"1-domain_suffix" : "direct",
"1-fb_pixel_id" : "direct",
"1-adobe_analytics_id" : "direct",
"3-sitemap_entries" : "direct",
"3-ipms_domain_iprangeowner_cidr" : "direct",
"3-ipms_domain_iprangeowner_ownerName" : "direct",
"3-ipms_domain_iprangeowner_address" : "direct",
"3-ipms_domain_nameserver" : "direct",
"3-ipms_domain_otheripused" : "direct",
"3-ipms_siteonthisip_now" : "direct",
"3-ipms_siteonthisip_before" : "direct",
"3-ipms_siteonthisip_broken" : "direct",
"3-ipms_useragents" : "direct",
"1-ip_shodan_hostnames" : "direct",
"3-ip_shodan_ports" : "iou",
"2-ip_shodan_vuln" : "iou",
"3-ip_shodan_cpe" : "iou",
"1-ga_id" : "direct",
"1-ga_tag_id" : "direct",
"1-ip" : "direct",
"1-verification_id" : "direct",
"1-yandex_tag_id" : "direct",
"2-subnet" : "direct",
"3-cdn-domain" : "direct",
"3-cms" : "direct",
"3-css_classes" : "iou",
"3-header-nonstd-value" : "direct",
"3-header-server" : "direct",
"3-id_tags" : "iou",
"3-iframe_id_tags" : "iou",
"3-link_href" : "iou",
"3-meta_generic" : "iou",
"3-meta_social" : "direct",
"3-script_src" : "iou",
"3-uuid" : "direct",
"3-whois_creation_date" : "direct",
"3-whois_server" : "direct",
"3-whois-registrar" : "direct",
"3-wp-blocks" : "iou",
"3-wp-categories" : "iou",
"3-wp-pages" : "iou",
"3-wp-posts" : "iou",
"3-wp-tags" : "iou",
"3-wp-users" : "iou",
"2-urlscan_globalvariable": "iou",
"2-urlscan_cookies": "iou",
"2-urlscan_consolemessages": "iou",
"2-urlscan_asn": "direct",
"2-urlscan_domainsonpage": "iou",
"2-urlscan_urlssonpage" : "iou",
"2-urlscanhrefs" : "iou",
"2-techstack" : "iou"
}

WHOIS_FEATURES = [
    "whois-registrar",
    "whois-whois_server",
    "whois-org",
    "whois-city",
    "whois-state",
    "whois-country",
]

URLSCAN_CERT_FEATURES = ["certificate-subjectName"]